import Navbar from "@/components/layout/Navbar"
import Link from "next/link"

export const metadata = {
  title: "Terms of Service | DevMentor AI",
  description: "The terms that govern your use of DevMentor AI.",
}

const lastUpdated = "March 2026"

const sections = [
  {
    id: "acceptance",
    title: "1. Acceptance of Terms",
    content:
      "By creating an account or using DevMentor AI in any way, you agree to be bound by these Terms of Service. If you do not agree, please do not use the platform. We reserve the right to update these terms at any time. Continued use after changes constitutes acceptance.",
  },
  {
    id: "service",
    title: "2. Description of Service",
    content:
      "DevMentor AI provides an AI-powered mentorship platform that includes personalised learning roadmap generation, AI code review, daily check-in tracking, concept explanation, and a community feed for self-taught developers. The platform is provided 'as-is'. AI-generated content is for educational guidance only and should not be treated as professional software engineering advice for production systems.",
  },
  {
    id: "eligibility",
    title: "3. Eligibility",
    content:
      "You must be at least 13 years old to use DevMentor AI. By using the service, you represent and warrant that you meet this requirement and that all information you provide is accurate and truthful.",
  },
  {
    id: "accounts",
    title: "4. Accounts & Security",
    content:
      "You are responsible for maintaining the confidentiality of your account credentials and for all activities under your account. Notify us immediately at olayeyeayomide2000@gmail.com if you suspect unauthorised access. We will never ask for your password by email. Accounts created with false information may be terminated without notice.",
  },
  {
    id: "plans",
    title: "5. Plans & Limits",
    content: "",
    table: {
      headers: ["Feature", "Free (Starter)", "Pro (Mentor) $12/mo", "Team (Cohort) $29/mo"],
      rows: [
        ["Roadmap generations", "1", "Unlimited", "Unlimited"],
        ["AI messages per day", "10", "Unlimited", "Unlimited"],
        ["Code reviews", "3/week", "Unlimited", "Unlimited"],
        ["Daily check-ins", "✓", "✓", "✓"],
        ["Conversation memory", "7 days", "Full history", "Full history"],
        ["Community access", "✓", "✓", "✓"],
        ["Priority AI responses", "Not included", "✓", "✓"],
        ["Team members", "1", "1", "Up to 5"],
        ["Shared roadmaps", "Not included", "Not included", "✓"],
      ],
    },
    after:
      "The Free plan is permanently free. No credit card is required to sign up. Upgrade prompts appear only when plan limits are reached, not before. We reserve the right to modify plan limits with 30 days' notice to existing users.",
  },
  {
    id: "acceptable-use",
    title: "6. Acceptable Use",
    content:
      "You agree not to: use the platform to generate content that is harmful, abusive, illegal, or deceptive; attempt to reverse-engineer, exploit, or overload our AI infrastructure; submit code containing malware, exploits, or data exfiltration logic; create multiple accounts to circumvent plan limits; share account credentials with others; or resell or commercially redistribute AI-generated content from DevMentor AI.",
  },
  {
    id: "ai-content",
    title: "7. AI-Generated Content",
    content:
      "AI responses on DevMentor AI are generated by Google's Gemini API and are provided for educational purposes only. They may contain errors, outdated information, or advice that is not suitable for your specific situation. You are responsible for evaluating and verifying any code or guidance before using it in a production environment. DevMentor AI makes no warranty that AI responses are accurate, complete, or fit for any particular purpose.",
  },
  {
    id: "ip",
    title: "8. Intellectual Property",
    content:
      "The DevMentor AI brand, interface, and proprietary prompt engineering are the intellectual property of DevMentor AI. Code you submit for review remains yours. AI-generated roadmaps and explanations are provided for your personal use: you may not commercially redistribute them. Any feedback you provide about the platform may be used to improve the service without compensation.",
  },
  {
    id: "termination",
    title: "9. Termination",
    content:
      "You may delete your account at any time via the dashboard settings. We may suspend or terminate your account if you violate these Terms, engage in fraudulent activity, or abuse platform resources. Upon termination, your data will be deleted within 30 days per our Privacy Policy.",
  },
  {
    id: "liability",
    title: "10. Limitation of Liability",
    content:
      "To the maximum extent permitted by law, DevMentor AI shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of income, data, or business opportunities, arising from your use of or inability to use the platform. Our total liability to you for any claims arising from these Terms shall not exceed the total amounts paid by you in the 12 months preceding the claim.",
  },
  {
    id: "changes",
    title: "11. Changes to These Terms",
    content:
      "We may update these Terms from time to time. When we make material changes, we will notify you via the email address on your account and update the 'Last Updated' date above. Your continued use of the platform after changes take effect constitutes acceptance of the revised Terms.",
  },
  {
    id: "contact",
    title: "12. Contact",
    content:
      "Questions about these Terms? Contact us at olayeyeayomide2000@gmail.com. We typically respond within 2 business days.",
  },
]

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background-light">
      <Navbar />

      {/* Hero */}
      <section className="pt-24 pb-16 px-6 border-b border-primary/5 bg-white">
        <div className="max-w-3xl mx-auto">
          <span className="inline-block px-4 py-1.5 bg-accent-coral/10 text-accent-coral text-xs font-black rounded-full mb-5 uppercase tracking-widest border border-accent-coral/10">
            Legal
          </span>
          <h1 className="text-5xl font-black tracking-tight mb-4 leading-tight">
            Terms of Service
          </h1>
          <p className="text-text-body">
            Last updated: <strong>{lastUpdated}</strong>
          </p>
          <p className="text-text-body mt-4 leading-relaxed">
            Please read these terms carefully before using DevMentor AI. They govern your access to and use of the platform.
          </p>
        </div>
      </section>

      {/* Content */}
      <section className="py-16 px-6">
        <div className="max-w-3xl mx-auto">
          {/* Table of Contents */}
          <div className="bg-white rounded-2xl border border-primary/5 shadow-soft p-6 mb-12">
            <p className="text-xs font-black uppercase tracking-wider text-slate-400 mb-4">Contents</p>
            <ul className="space-y-2">
              {sections.map((s) => (
                <li key={s.id}>
                  <a
                    href={`#${s.id}`}
                    className="text-sm font-bold hover:text-accent-coral transition-colors flex items-center gap-2"
                  >
                    <span className="material-symbols-outlined text-sm text-accent-coral">arrow_forward</span>
                    {s.title}
                  </a>
                </li>
              ))}
            </ul>
          </div>

          {/* Sections */}
          <div className="space-y-14">
            {sections.map((section) => (
              <div key={section.id} id={section.id}>
                <h2 className="text-2xl font-black mb-6 pb-4 border-b border-primary/5">
                  {section.title}
                </h2>
                {section.content && (
                  <p className="text-text-body text-sm leading-relaxed">{section.content}</p>
                )}
                {section.table && (
                  <div className="mt-4 mb-6 overflow-x-auto rounded-2xl border border-primary/5 shadow-soft">
                    <table className="w-full text-sm">
                      <thead>
                        <tr className="bg-slate-50 border-b border-primary/5">
                          {section.table.headers.map((h) => (
                            <th
                              key={h}
                              className="text-left px-5 py-3.5 font-black text-xs uppercase tracking-wider text-slate-500"
                            >
                              {h}
                            </th>
                          ))}
                        </tr>
                      </thead>
                      <tbody>
                        {section.table.rows.map((row, ri) => (
                          <tr
                            key={ri}
                            className="border-b border-primary/5 last:border-0 hover:bg-slate-50/50 transition-colors"
                          >
                            {row.map((cell, ci) => (
                              <td
                                key={ci}
                                className={`px-5 py-3.5 ${ci === 0 ? "font-bold text-slate-900" : "text-text-body"}`}
                              >
                                {cell}
                              </td>
                            ))}
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                )}
                {section.after && (
                  <p className="text-text-body text-sm leading-relaxed mt-4">{section.after}</p>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="py-8 px-6 border-t border-primary/5 text-center">
        <p className="text-xs text-text-body">
          © {new Date().getFullYear()} DevMentor AI ·{" "}
          <Link href="/about" className="hover:text-primary transition-colors">About</Link>
          {" · "}
          <Link href="/privacy" className="hover:text-primary transition-colors">Privacy</Link>
          {" · "}
          <Link href="/careers" className="hover:text-primary transition-colors">Careers</Link>
        </p>
      </footer>
    </div>
  )
}
